### ISSUE TITLE
Issues with dependency management

### ISSUE THREAD

**Issue by textbook** [CodeYourFuture/Full-Stack-Project-Assessment#27]
- `client/yarn.lock` suggests that Yarn should be used
- `server/package-lock.json` suggests that NPM should be used

The syllabus only covers the latter, so the CRA app should be migrated over - I _think_ it's just a matter of deleting `yarn.lock`, `npm install`ing and committing the `package-lock.json` instead, none of the scripts reference `npm`/`yarn`.

Also `server/node_modules/` is under version control, we need a `.gitignore` somewhere.

**Comment by Dedekind561** [comment]
Both server and client make use of `npm` now following one of the recent upgrades.
